Attribute VB_Name = "Module1"
Public zdrw As Boolean
Public sjkz As Boolean
Public kbdh As Boolean
Public sxkg As Boolean
Public sjms As Boolean
Public mode As Boolean
Public ksms As Boolean
Public zxms As Boolean
Public zdms As Boolean
Public bbms As Boolean
Public kjzs As Boolean
Public cyc As Boolean
Public caidan As Boolean
Public leftt As Integer
Public toumd As Integer
Public tmdu As Integer
Public xtbb As Integer
Public fricls As Integer
Public fdctime As Integer
Public kbcout As Integer
Public hkcout As Integer
Public hktext As String
Public fdctext As String
Public kbtext As String
Public kbcolr As String
Public theme As String
Public imgname As String
Public textc As String
Public dtrs As String
Public aud As String
Public dt As String
Public h As String
Public m As String
Public s As String
Public lszr As String
Public sjmm As String
Public zy1 As String
Public zy2 As String
Public cyn As String
